trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  projectFolder: 'src/Notes.Web'
  buildOutputFolder: '/src/Notes.Web/build'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  
- script: |
    pushd $(projectFolder) && npm install && popd
    pushd $(projectFolder) && npm run build && popd

- task: AzureRmWebAppDeployment@3
  displayName: 'Azure App Service Deploy: apex-prod-uksouth-notes-wev'
  inputs:
    azureSubscription: 'Visual Studio Professional with MSDN(7e4901b5-30dc-42df-9d94-01b9f128322e)'
    WebAppName: 'apex-prod-uksouth-notes-web'
    Package: '$(System.DefaultWorkingDirectory)/src/Notes.Web/build'
    packageForLinux: '$(System.DefaultWorkingDirectory)/src/Notes.Web/build'