trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  demands: npm

variables:
  projectFolder: 'src/Notes.Web'
  buildOutputFolder: 'src/Notes.Web/build'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false
    workingDir: 'src/Notes.Web'

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'
    workingDir: 'src/Notes.Web'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(buildOutputFolder)' 
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/src/Notes.Web/build
    artifact: 'drop'
    publishLocation: 'pipeline'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Professional with MSDN(7e4901b5-30dc-42df-9d94-01b9f128322e)'
    appType: 'webAppLinux'
    WebAppName: 'apex-prod-uksouth-notes-web'
    packageForLinux: $(System.DefaultWorkingDirectory)/src/Notes.Web/build
    RuntimeStack: 'NODE|lts'