trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  demands: npm

variables:
  projectFolder: 'src/Notes.Web'
  buildOutputFolder: '/src/Notes.Web/build'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false
    workingDir: 'src/Notes.Web'

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'
    workingDir: 'src/Notes.Web'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: ‘$(System.DefaultWorkingDirectory)/build’
    TargetFolder: ‘$(Build.ArtifactStagingDirectory)’

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
