trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  
- script: |
    cd src/Node.Web
    npm run install 
    npm run build 
  displayName: 'npm install, build and test'
  env:
    CI: true